const ASSET = './public/assets/';
const products = [
  {id:'skates',name:'Low Profile Console Skates',desc:'A steady fit for current-generation consoles.',price:24,was:32,cats:['PlayStation','Stands'],badge:'25% OFF',rating:'4.8',img:'mounting-kit.webp',position:'20% 79%'},
  {id:'plates',name:'Matte Console Shell',desc:'A clean new finish for your console.',price:48,cats:['PlayStation','Plates'],badge:'NEW',rating:'4.7',img:'hero-gaming.webp',position:'77% 44%'},
  {id:'mount',name:'Stealth Desk Mount',desc:'Get your console off the desk and out of the way.',price:34,cats:['PlayStation','Xbox','Mounts'],badge:'BEST SELLER',rating:'4.9',img:'mounting-kit.webp',position:'50% 47%'},
  {id:'dustkit',name:'Console Dust Cover Set',desc:'Simple protection for ports and vents.',price:15,cats:['PlayStation','Xbox'],badge:'',rating:'4.6',img:'accessories-studio.webp',position:'78% 82%'},
  {id:'headset',name:'Magnetic Headset Hook',desc:'Keep your headset close and surfaces clear.',price:19,cats:['Xbox','Hooks'],badge:'',rating:'4.8',img:'accessories-studio.webp',position:'79% 32%'},
  {id:'vrgrip',name:'VR Controller Grip Kit',desc:'A secure, comfortable hold for longer sessions.',price:29,cats:['VR'],badge:'',rating:'4.7',img:'vr-display.webp',position:'50% 71%'},
  {id:'stand',name:'Universal Console Stand',desc:'Stable support with room for airflow.',price:22,cats:['PlayStation','Xbox','Stands'],badge:'',rating:'4.8',img:'mounting-kit.webp',position:'50% 75%'},
  {id:'wall',name:'Universal Wall Mount',desc:'A compact mount for consoles and controllers.',price:27,cats:['PlayStation','Xbox','Mounts'],badge:'',rating:'4.7',img:'mounting-kit.webp',position:'51% 43%'},
  {id:'switchdock',name:'Switch Dock Organizer',desc:'Keep your portable setup together.',price:25,cats:['Nintendo','Stands'],badge:'',rating:'4.6',img:'hero-gaming.webp',position:'72% 55%'},
  {id:'vrstand',name:'VR Headset Display Stand',desc:'A considered home for your headset.',price:32,cats:['VR','Stands'],badge:'',rating:'4.9',img:'vr-display.webp',position:'50% 81%'},
  {id:'hookset',name:'Controller Hook Pair',desc:'Two magnetic hooks for a tidy setup.',price:18,cats:['PlayStation','Xbox','Hooks'],badge:'',rating:'4.8',img:'mounting-kit.webp',position:'67% 85%'},
  {id:'cable',name:'Cable Tidy Kit',desc:'Small details for a cleaner desk.',price:12,cats:['PlayStation','Xbox','Nintendo'],badge:'',rating:'4.5',img:'accessories-studio.webp',position:'70% 90%'}
];
const featuredIds=['skates','plates','mount','dustkit','headset','vrgrip','stand','wall'];
const features=[
  {tag:'DESIGNED FOR YOUR DESK',title:'A better way to make room.',copy:'The Stealth Desk Mount keeps your console secure and gives your setup a little breathing room. Clean lines. Easy access. No clutter.',id:'mount',img:'accessories-studio.webp',pos:'19% 40%'},
  {tag:'PLAY WITHOUT THE CLUTTER',title:'Keep your next session close.',copy:'A place for every piece of gear. Store your headset and controllers where they belong, then get straight back to play.',id:'headset',img:'hero-gaming.webp',pos:'90% 25%'},
  {tag:'READY WHEN YOU ARE',title:'Little details. Better play.',copy:'Thoughtful stands and tidy storage, made to work with the gear you already love.',id:'stand',img:'accessories-studio.webp',pos:'23% 79%'},
  {tag:'BUILT AROUND YOUR SPACE',title:'Clear your desk. Keep your gear.',copy:'Make your setup feel more intentional with simple mounting solutions designed for everyday gaming.',id:'wall',img:'hero-gaming.webp',pos:'77% 59%'},
  {tag:'A CLEANER WAY TO PLAY',title:'Your space, set up right.',copy:'Give your console a steady home and leave more room for the things you use every day.',id:'skates',img:'accessories-studio.webp',pos:'14% 80%'}
];
const $=(q,root=document)=>root.querySelector(q), $$=(q,root=document)=>[...root.querySelectorAll(q)];
const money=n=>'$'+Number(n).toFixed(2);
const viewIds=['home','collection','product','search','page'];
const cart=(()=>{try{return JSON.parse(localStorage.getItem('novaCart')||'[]')}catch{return []}})();
let currentProduct=products[0],heroIndex=0,featureIndex=0,heroTimer=null,toastTimer=null;
function saveCart(){localStorage.setItem('novaCart',JSON.stringify(cart));updateCartUI()}
function productBy(id){return products.find(p=>p.id===id)||products[0]}
function cardMarkup(p){return `<article class="product-card"><a class="product-thumb" href="#product?id=${p.id}" aria-label="View ${p.name}"><img src="${ASSET+p.img}" style="object-position:${p.position}" alt="${p.name}" loading="lazy"/>${p.badge?`<span class="product-badge">${p.badge}</span>`:''}</a><button class="quick-add" data-add="${p.id}" aria-label="Add ${p.name} to bag">＋</button><div class="product-card-info"><div class="product-title-row"><div><h3><a href="#product?id=${p.id}">${p.name}</a></h3><p>${p.desc}</p></div><span class="product-price">${money(p.price)}</span></div><div class="product-rating">★★★★★ <span>${p.rating}</span></div><div class="swatches" aria-label="Available colors"><i class="swatch black"></i><i class="swatch white"></i>${p.id==='vrgrip'?'<i class="swatch green"></i>':''}</div></div></article>`}
function initHome(){
  $('#featured-products').innerHTML=featuredIds.map(id=>cardMarkup(productBy(id))).join('');
  drawHeroPips(); drawFeature();
}
function drawHeroPips(){const el=$('.hero-pips');el.innerHTML=Array.from({length:5},(_,i)=>`<button class="hero-pip ${i===heroIndex?'active':''}" aria-label="Go to slide ${i+1}" data-hero="${i}"></button>`).join('');$('.hero-index').innerHTML=`0${heroIndex+1} <i>/</i> 05`}
function setHero(n){heroIndex=(n+5)%5;const hero=$('.hero'),slides=[{title:'Make room<br/>for <em>better play.</em>',copy:'Thoughtful gaming accessories. Cleaner spaces. More time in the game.',image:'hero-gaming.webp'},{title:'Keep your<br/><em>space in play.</em>',copy:'Clear the desk and keep your console right where you need it.',image:'mounting-kit.webp'},{title:'Your setup,<br/><em>thoughtfully done.</em>',copy:'Well-considered gear for the details around the game.',image:'accessories-studio.webp'},{title:'Find your<br/><em>next level.</em>',copy:'Bring your headset and controllers together, ready for the next session.',image:'vr-display.webp'},{title:'Gear up.<br/><em>Settle in.</em>',copy:'A little more space for everything that makes game night yours.',image:'hero-gaming.webp'}],slide=slides[heroIndex];hero.classList.add('changing');$('.hero-bg').style.setProperty('--hero-img',`url("${ASSET+slide.image}")`);$('.hero-title').innerHTML=slide.title;$('.hero-copy').textContent=slide.copy;drawHeroPips();setTimeout(()=>hero.classList.remove('changing'),280)}
function drawFeature(){const f=features[featureIndex];$('#spotlight-stage').innerHTML=`<div class="spotlight-image"><img src="${ASSET+f.img}" alt="${f.title}" style="object-position:${f.pos}" loading="lazy"/></div><div class="spotlight-copy"><div class="eyebrow">${f.tag}</div><h3>${f.title}</h3><p>${f.copy}</p><a class="button button-dark" href="#product?id=${f.id}">Explore the gear <span>↗</span></a></div>`;$('#spotlight-dots').innerHTML=features.map((_,i)=>`<button class="${i===featureIndex?'active':''}" data-feature="${i}" aria-label="Show feature ${i+1}"></button>`).join('')}
function cartProduct(item){return item.bundle?{id:'bundle',name:'Custom setup bundle',price:item.price,img:'accessories-studio.webp',position:'center'}:productBy(item.id)}
function updateCartUI(){const count=cart.reduce((n,x)=>n+x.qty,0);$('.cart-count').textContent=count;$('.drawer-count').textContent=`(${count})`;$('.cart-items').innerHTML=cart.map(x=>{const p=cartProduct(x);return `<div class="cart-row"><img src="${ASSET+p.img}" style="object-position:${p.position}" alt="${p.name}"/><div class="cart-row-info"><h3>${p.name}</h3><small>${x.variant||'Black'}</small><div class="cart-row-controls"><button data-cart-qty="${x.id}" data-delta="-1" aria-label="Decrease ${p.name}">−</button><span>${x.qty}</span><button data-cart-qty="${x.id}" data-delta="1" aria-label="Increase ${p.name}">＋</button><button class="remove" data-remove="${x.id}">Remove</button></div></div><span class="cart-row-price">${money(p.price*x.qty)}</span></div>`}).join('');const total=cart.reduce((n,x)=>n+cartProduct(x).price*x.qty,0);$('.cart-subtotal').textContent=money(total);$('.cart-empty').classList.toggle('hidden',count>0);$('.cart-summary').classList.toggle('hidden',count===0);$('.drawer-promo').innerHTML=total>=40?'You unlocked <b>free shipping.</b>':`You're <b>${money(40-total)}</b> away from free shipping.`}
function showToast(message){const t=$('.toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}
function addToCart(id,qty=1,variant='Black'){const found=cart.find(x=>x.id===id&&x.variant===variant);if(found)found.qty+=qty;else cart.push({id,qty,variant});saveCart();showToast('Added to your bag');}
function openCart(){closeMobile();$('.overlay').classList.add('open');$('.cart-drawer').classList.add('open');$('.cart-drawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeCart(){ $('.overlay').classList.remove('open');$('.cart-drawer').classList.remove('open');$('.cart-drawer').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function openSearch(){closeMobile();$('.search-overlay').classList.add('open');setTimeout(()=>$('#search-overlay-input').focus(),220)}function closeSearch(){$('.search-overlay').classList.remove('open')}
function closeMobile(){$('.mobile-menu').classList.remove('open');$('.mobile-menu').setAttribute('aria-hidden','true');$('.menu-toggle').setAttribute('aria-expanded','false');$('.overlay').classList.remove('menu-open');if(!$('.cart-drawer').classList.contains('open')){$('.overlay').classList.remove('open');document.body.style.overflow=''}}
function selectedCategory(){const qs=location.hash.split('?')[1]||'';return new URLSearchParams(qs).get('cat')||'All accessories'}
function renderCollection(){const cat=selectedCategory();$('#collection-title').textContent=cat==='All accessories'?'All accessories':`${cat} accessories`;let list=products.filter(p=>cat==='All accessories'||p.cats.includes(cat));const active=[...$$('.filter-check:checked')].map(x=>x.value);if(active.length)list=list.filter(p=>active.some(x=>p.cats.includes(x)));const sort=$('#sort-select').value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='title')list.sort((a,b)=>a.name.localeCompare(b.name));$('#product-result-count').textContent=`${list.length} products`;$('#collection-grid').innerHTML=list.length?list.map(cardMarkup).join(''):'<div class="empty-results">No products match these filters.</div>';$$('.filter-check').forEach(x=>x.checked=active.includes(x.value));}
function renderProduct(id){const p=currentProduct=productBy(id);$('#product-breadcrumb').textContent=p.name;$('#product-title').textContent=p.name;$('#product-type').textContent=`NOVA GEAR / ${p.cats[0].toUpperCase()}`;$('#product-price').textContent=money(p.price);$('#product-desc').textContent=p.desc+' Designed to help your space work a little better, with a compact footprint and considered everyday details.';$('#accordion-description').textContent=p.desc+' Pair with other pieces from the NOVA GEAR range to build a setup that fits your space.';const img=$('#product-main-image');img.src=ASSET+p.img;img.style.objectPosition=p.position;$$('.thumb img').forEach((el,i)=>{el.src=ASSET+(i===1?'hero-gaming.webp':p.img);el.style.objectPosition=p.position});$('#product-qty').value=1;$('#related-products').innerHTML=products.filter(x=>x.id!==p.id).slice(0,6).map(cardMarkup).join('')}
const pageCopy={about:['About NOVA GEAR','We make small, thoughtful additions that help gaming setups feel calmer, cleaner, and ready for more. NOVA GEAR is an independent concept store for the things around the game.'],journal:['The NOVA Journal','Ideas for your space, practical setup guides, and notes on the details that make everyday play feel better.'],contact:['Contact us','Need help with a product or have a question about a setup? Send a note to hello@novagear.example. This demo storefront does not receive or process messages.'],shipping:['Shipping & delivery','Orders in this demo are not fulfilled. Delivery information shown here is sample content for the storefront prototype.'],returns:['Returns','This is a demonstration storefront. No products are sold or shipped and no orders are created.'],faq:['Frequently asked questions','Explore compatibility, setup tips, and product details in the demo catalogue. No payment, account, or order system is connected.'],privacy:['Privacy policy','This independent NOVA GEAR demonstration does not collect form submissions or send your information to a backend.'],terms:['Terms of service','This site is a non-transactional demonstration. Checkout controls do not create or confirm a purchase.']};
function renderRoute(){let hash=decodeURIComponent(location.hash||'#home');const [route,query='']=hash.slice(1).split('?');viewIds.forEach(id=>$('#view-'+id).classList.add('hidden'));if(route==='collection'){ $('#view-collection').classList.remove('hidden');renderCollection()}else if(route==='product'){ $('#view-product').classList.remove('hidden');renderProduct(new URLSearchParams(query).get('id'))}else if(route==='search'){ $('#view-search').classList.remove('hidden');renderSearch('')}else if(route==='page'){ $('#view-page').classList.remove('hidden');const name=(new URLSearchParams(query).get('name')||'About').toLowerCase();const d=pageCopy[name]||[name.charAt(0).toUpperCase()+name.slice(1),'Stories and details from the NOVA GEAR world.'];$('#info-title').textContent=d[0];$('#info-copy').textContent=d[1]}else{$('#view-home').classList.remove('hidden')}window.scrollTo({top:0,behavior:'smooth'});closeMobile();closeSearch();}
function renderSearch(q){const term=q.trim().toLowerCase();const list=term?products.filter(p=>(p.name+' '+p.desc+' '+p.cats.join(' ')).toLowerCase().includes(term)):[];$('#search-results').innerHTML=term?(list.length?list.map(cardMarkup).join(''):'<p>No products found. Try “mount”, “stand”, or “VR”.</p>'):''}
function startHero(){clearInterval(heroTimer);heroTimer=setInterval(()=>{if(!document.hidden&&!$('.hero-pause').classList.contains('paused'))setHero(heroIndex+1)},6200)}
initHome();updateCartUI();startHero();
window.addEventListener('hashchange',renderRoute);renderRoute();
window.addEventListener('scroll',()=>$('.site-header').classList.toggle('scrolled',window.scrollY>12),{passive:true});
let heroTouchStart=0;$('.hero').addEventListener('touchstart',e=>{heroTouchStart=e.changedTouches[0].clientX},{passive:true});$('.hero').addEventListener('touchend',e=>{const delta=e.changedTouches[0].clientX-heroTouchStart;if(Math.abs(delta)>55)setHero(heroIndex+(delta<0?1:-1))},{passive:true});
document.addEventListener('click',e=>{
 const t=e.target.closest('button,a,.overlay');if(!t)return;
 if(t.matches('.has-menu > .nav-link')){const item=t.closest('.has-menu'),open=!item.classList.contains('menu-open');$$('.nav-item.menu-open').forEach(x=>{x.classList.remove('menu-open');x.querySelector('.nav-link')?.setAttribute('aria-expanded','false')});item.classList.toggle('menu-open',open);t.setAttribute('aria-expanded',String(open))}
 if(t.matches('[data-hero]'))setHero(Number(t.dataset.hero));
 if(t.matches('.hero-pause')){t.classList.toggle('paused');t.textContent=t.classList.contains('paused')?'▶':'Ⅱ'}
 if(t.matches('[data-slide="products"]'))$('#featured-products').scrollBy({left:Number(t.dataset.dir)*$('#featured-products').clientWidth*.8,behavior:'smooth'});
 if(t.matches('[data-slide="spotlight"]')){featureIndex=(featureIndex+Number(t.dataset.dir)+features.length)%features.length;drawFeature()}
 if(t.matches('[data-feature]')){featureIndex=Number(t.dataset.feature);drawFeature()}
 if(t.matches('.bundle-option')){$$('.bundle-option').forEach(x=>x.classList.remove('selected'));t.classList.add('selected');bundleTotal()}
 if(t.matches('.bundle-add')){let base=Number($('.bundle-option.selected').querySelector('strong').textContent.replace('$',''));$$('.bundle-addons input:checked').forEach(x=>base+=Number(({controller:18,headset:16,feet:12})[x.dataset.addon]));cart.push({id:'bundle',qty:1,variant:$('.bundle-option.selected').querySelector('b').textContent,price:base,bundle:true});saveCart();openCart()}
 if(t.matches('.quick-add')){e.preventDefault();addToCart(t.dataset.add);}
 if(t.matches('[data-add]')){addToCart(t.dataset.add)}
 if(t.matches('.cart-open'))openCart();
 if(t.matches('.drawer-close'))closeCart();if(t.matches('.overlay')){if(t.classList.contains('menu-open'))closeMobile();else closeCart()}
 if(t.matches('.continue-shopping')){closeCart();location.hash='#collection'}
 if(t.matches('[data-remove]')){const i=cart.findIndex(x=>x.id===t.dataset.remove);if(i>=0)cart.splice(i,1);saveCart()}
 if(t.matches('[data-cart-qty]')){const x=cart.find(i=>i.id===t.dataset.cartQty);if(x){x.qty+=Number(t.dataset.delta);if(x.qty<1)cart.splice(cart.indexOf(x),1)}saveCart()}
 if(t.matches('.demo-checkout'))showToast('Demo only — no order or payment was created.');
 if(t.matches('.search-open'))openSearch();if(t.matches('.search-close'))closeSearch();
 if(t.matches('.menu-toggle')){const m=$('.mobile-menu');const open=!m.classList.contains('open');m.classList.toggle('open',open);m.setAttribute('aria-hidden',String(!open));t.setAttribute('aria-expanded',String(open));if(open){$('.overlay').classList.add('open','menu-open');document.body.style.overflow='hidden'}else closeMobile()}
 if(t.matches('.mobile-close'))closeMobile();
 if(t.matches('.account-open'))showToast('Account services are not connected in this demo.');
 if(t.matches('.filter-toggle'))$('.filter-panel').classList.toggle('hidden');
 if(t.matches('.clear-filters')){$$('.filter-check').forEach(x=>x.checked=false);renderCollection()}
 if(t.matches('.gallery-next')||t.matches('.gallery-prev')){const img=$('#product-main-image');img.src=img.src.includes('hero-gaming')?ASSET+currentProduct.img:ASSET+'hero-gaming.webp'}
 if(t.matches('.thumb')){$$('.thumb').forEach(x=>x.classList.remove('active'));t.classList.add('active');const im=t.querySelector('img');$('#product-main-image').src=im.src;$('#product-main-image').style.objectPosition=im.style.objectPosition||currentProduct.position}
 if(t.matches('.qty-up'))$('#product-qty').value=Number($('#product-qty').value||1)+1;
 if(t.matches('.qty-down'))$('#product-qty').value=Math.max(1,Number($('#product-qty').value||1)-1);
 if(t.matches('.product-add')){addToCart(currentProduct.id,Math.max(1,Number($('#product-qty').value)||1),$('#product-variant').value);openCart()}
 if(t.matches('.feed-card')){location.hash=`#product?id=${t.dataset.product}`}
});
function bundleTotal(){let total=Number($('.bundle-option.selected').querySelector('strong').textContent.replace('$',''));$$('.bundle-addons input:checked').forEach(x=>total+=({controller:18,headset:16,feet:12})[x.dataset.addon]);$('#bundle-total').textContent=money(total)}
document.addEventListener('change',e=>{if(e.target.matches('.bundle-addons input'))bundleTotal();if(e.target.matches('.filter-check'))renderCollection();if(e.target.matches('#sort-select'))renderCollection();if(e.target.matches('#product-variant')){const img=$('#product-main-image');img.src=e.target.value==='White'?ASSET+'hero-gaming.webp':ASSET+currentProduct.img;img.style.objectPosition=currentProduct.position}});
document.addEventListener('submit',e=>{if(e.target.matches('.search-form')){e.preventDefault();const term=e.target.querySelector('input[type="search"]')?.value||'';location.hash='#search';$('#search-query').value=term;setTimeout(()=>renderSearch(term),0);closeSearch()}else if(e.target.matches('.newsletter-form,.footer-email')){e.preventDefault();const input=e.target.querySelector('input');if(input?.checkValidity()){e.target.reset();showToast('Thanks for joining the NOVA list.')}}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closeSearch();closeMobile();$$('.nav-item.menu-open').forEach(x=>{x.classList.remove('menu-open');x.querySelector('.nav-link')?.setAttribute('aria-expanded','false')})}});
